[snowflake]
user = "your_username"
password = "your_password"
account = "your_account"
warehouse = "CX_WH"
database = "ANALYTICS"
schema = "PUBLIC"
role = "CUSTOMER_ANALYTICS_APP"

# Optional: Redis configuration for caching
[redis]
host = "localhost"
port = 6379
password = ""
db = 0

# Optional: Authentication settings
[auth]
enabled = false
provider = "okta"  # or "azure", "google", etc.
client_id = ""
client_secret = ""
redirect_uri = "http://localhost:8501" 