WITH HIGH_VALUE_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ANALYTICS.CUSTOMER_BASE
    WHERE LIFETIME_VALUE >= 1000
),
HIGH_VALUE_TOTAL_COUNT AS (
    SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_HV_COUNT
    FROM HIGH_VALUE_CUSTOMERS
),
HIGH_VALUE_HIGH_RISK_COUNT AS (
    SELECT COUNT(DISTINCT sig.CUSTOMER_ID) AS HV_HR_COUNT
    FROM ANALYTICS.CUSTOMER_PERSONA_SIGNALS sig
    JOIN HIGH_VALUE_CUSTOMERS hv ON sig.CUSTOMER_ID = hv.CUSTOMER_ID
    WHERE sig.CHURN_RISK = 'High'
)
SELECT
    COALESCE(
        (SELECT HV_HR_COUNT FROM HIGH_VALUE_HIGH_RISK_COUNT) * 100.0 / NULLIF((SELECT TOTAL_HV_COUNT FROM HIGH_VALUE_TOTAL_COUNT), 0),
    0) AS SHARE_HIGH_VALUE_IN_HIGH_RISK; 