WITH PERSONA_COUNTS AS (
    SELECT
        DERIVED_PERSONA,
        COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
    FROM ANALYTICS.CUSTOMER_PERSONA_SIGNALS
    WHERE DERIVED_PERSONA IS NOT NULL -- Ensure persona is not null
    GROUP BY DERIVED_PERSONA
),
RANKED_PERSONAS AS (
    SELECT
        DERIVED_PERSONA,
        CUSTOMER_COUNT,
        RANK() OVER (ORDER BY CUSTOMER_COUNT DESC, DERIVED_PERSONA ASC) as RNK -- Add DERIVED_PERSONA to break ties consistently
    FROM PERSONA_COUNTS
)
SELECT DERIVED_PERSONA, CUSTOMER_COUNT FROM RANKED_PERSONAS WHERE RNK = 1 LIMIT 1; 