SELECT
    COALESCE(
        SUM(CASE WHEN CHURN_RISK = 'High' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(DISTINCT CUSTOMER_ID), 0),
    0) AS HIGH_CHURN_RISK_PERCENTAGE
FROM ANALYTICS.CUSTOMER_PERSONA_SIGNALS; 