SELECT
    COALESCE(SUM(cb.LIFETIME_VALUE), 0) AS TOTAL_LTV_AT_RISK
FROM ANALYTICS.CUSTOMER_PERSONA_SIGNALS cps
JOIN ANALYTICS.CUSTOMER_BASE cb ON cps.CUSTOMER_ID = cb.CUSTOMER_ID
WHERE cps.CHURN_RISK = 'High'; 