WITH BaseData AS (
    SELECT
        cps.CUSTOMER_ID,
        cps.DERIVED_PERSONA,
        cps.CHURN_RISK,
        cb.LIFETIME_VALUE
    FROM ANALYTICS.CUSTOMER_PERSONA_SIGNALS cps
    JOIN ANALYTICS.CUSTOMER_BASE cb ON cps.CUSTOMER_ID = cb.CUSTOMER_ID
),
DominantPersonaCalc AS (
    SELECT
        DERIVED_PERSONA,
        COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
    FROM BaseData
    WHERE DERIVED_PERSONA IS NOT NULL
    GROUP BY DERIVED_PERSONA
    ORDER BY CUSTOMER_COUNT DESC, DERIVED_PERSONA ASC
    LIMIT 1
),
HighValueCustomerPercentageCalc AS (
    SELECT
        SUM(CASE WHEN LIFETIME_VALUE > 1000 THEN 1 ELSE 0 END) * 100.0 / COUNT(DISTINCT CUSTOMER_ID) AS HIGH_VALUE_CUSTOMER_PERCENTAGE
    FROM BaseData
),
HighValueChurnRiskShareCalc AS (
    SELECT
        COALESCE(
            SUM(CASE WHEN LIFETIME_VALUE >= 1000 AND CHURN_RISK = 'High' THEN 1 ELSE 0 END) * 100.0 /
            NULLIF(SUM(CASE WHEN LIFETIME_VALUE >= 1000 THEN 1 ELSE 0 END), 0),
        0) AS SHARE_HIGH_VALUE_IN_HIGH_RISK
    FROM BaseData
),
TotalLTVAtRiskCalc AS (
    SELECT
        COALESCE(SUM(CASE WHEN CHURN_RISK = 'High' THEN LIFETIME_VALUE ELSE 0 END), 0) AS TOTAL_LTV_AT_RISK
    FROM BaseData
)
SELECT
    (SELECT DERIVED_PERSONA FROM DominantPersonaCalc) AS DOMINANT_PERSONA_NAME,
    (SELECT CUSTOMER_COUNT FROM DominantPersonaCalc) AS DOMINANT_PERSONA_COUNT,
    (SELECT HIGH_VALUE_CUSTOMER_PERCENTAGE FROM HighValueCustomerPercentageCalc) AS HIGH_VALUE_CUSTOMER_PERCENTAGE,
    (SELECT SHARE_HIGH_VALUE_IN_HIGH_RISK FROM HighValueChurnRiskShareCalc) AS SHARE_HIGH_VALUE_IN_HIGH_RISK,
    (SELECT TOTAL_LTV_AT_RISK FROM TotalLTVAtRiskCalc) AS TOTAL_LTV_AT_RISK; 